### ISSUE TITLE
Markup not visible after cloning of scene loading

### ISSUE THREAD

**Issue by cpinter** [SlicerHeart/SlicerSurfaceMarkup#1] opened 2021-11-08 11:49 UTC

**Comment by lassoan** [comment] 2021-12-15 13:17
Do you mean the control points are not visible?

**Comment by cpinter** [comment] 2021-12-15 13:33
I can't remember, it was quite broken though. I can check it out if you want.

For now I'm looking at fitting surface on arbitrary model. A grid with known size is needed unfortunately.

**Comment by lassoan** [comment] 2021-12-15 14:56
I cannot reproduce this issue anymore. Tested both with local builds and the latest official build.

The case that I've come across was due to glyph scale was set to 0 (probably intentionally, just to improve visual appearance).

It works well even if I specify a scene as command-line argument when starting Slicer (so there is no issue with registering the node type or widget too late).

I close this and we can reopen if we encounter it again.

**Comment by cpinter** [comment] 2021-12-15 14:56
Great, thanks!

**Closed by lassoan** 2021-12-15 14:56 UTC
Labels: bug
